### ISSUE TITLE
Cannot run all your docker-compose files at the same time. Either it is due to file not found error or something is wrong with Kafka

### ISSUE THREAD

**Issue by methisstud** [lapis2002/gh-archive-data-pipeline#8] opened 2024-03-21 09:44 UTC

**Comment by lapis2002** [comment] 2024-03-21 09:50
Can you share the error logs/screenshots?

**Comment by lapis2002** [comment] 2024-03-27 20:05
I couldn't reproduce the bug so I'll close the issue.

**Closed as completed by lapis2002** 2024-03-27 20:05 UTC
